updated to realize search, return results and display detailed weather info
hpyhacking/algonquin-college-weather-station pull request #13
Opened 2022-12-05 19:24 UTC by Pengyong-Zhan

1. added a section for search and return a result list in index.html
2. added 3 sections to display detailed weather info 
3. updated search.js, weather.js(modules) and weather.js(pages)
4. added an import clause in index.js

2022-12-05 20:54 UTC, hpyhacking requested changes

2022-12-05 20:54 UTC, hpyhacking commented on src/app/pages/weather.js
> +        $('#detailsUl').append(liWindSpeed);
same as above

2022-12-05 20:54 UTC, hpyhacking commented on src/app/ui/search.js
> +    }
this should be a page logic, could not shown in a ui module

2022-12-05 20:54 UTC, hpyhacking commented on src/index.js
> +import "./app/ui/search.js"
why add ui module in here?

ui module should be required in a page module, and use a element to call the ui module function.

2022-12-06 00:57 UTC, Pengyong-Zhan commented on src/app/modules/weather.js
> +    console.log("test request");
ok

2022-12-06 20:36 UTC, hpyhacking commented
merged in #14

2022-12-06 20:36 UTC, closed without merging